--Cambio 8 de Febrero 2015
ALTER TABLE Clientes ADD TipoSocio VARCHAR(20) NOT NULL
ALTER TABLE Clientes ADD NumeroSocio VARCHAR(11) NULL
--Cambio 9 de Febrero 2015
ALTER TABLE Clientes ADD EmpresaTelefonoExt INT NULL
--Cambio 16 de Febrero 2015
ALTER TABLE Clientes ALTER COLUMN TelefonoMovil VARCHAR(19) NULL
ALTER TABLE Clientes ADD EmpresaEstado CHAR(2) NULL FOREIGN KEY REFERENCES Estados(ID)
ALTER TABLE Clientes ADD EmpresaMunicipio CHAR(4) NULL FOREIGN KEY REFERENCES Municipios(ID)
ALTER TABLE CLIENTES DROP COLUMN EMPRESACALLES
ALTER TABLE CLIENTES ADD  EMPRESACALLE VARCHAR(100)
ALTER TABLE CLIENTES ALTER COLUMN Profesion CHAR(7) NULL 

ALTER TABLE Clientes DROP CONSTRAINT FK__Clientes__Usuari__5F141958
ALTER TABLE Clientes DROP COLUMN Usuario


ALTER TABLE Clientes ADD Usuario VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Usuarios(ID) DEFAULT('orlando')
ALTER TABLE Clientes ADD UsuarioAlta VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Usuarios(ID) DEFAULT('orlando')
ALTER TABLE Clientes ADD FechaAlta SMALLDATETIME NOT NULL DEFAULT GETDATE()
ALTER TABLE Clientes ADD UsuarioModificacion VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Usuarios(ID) DEFAULT('orlando')
ALTER TABLE Clientes ADD FechaModificacion SMALLDATETIME NOT NULL DEFAULT GETDATE()